name: Python Application CI/CD

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.DEV_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        
      shell: bash  

    - name: Test Connection
      run: ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key hp@"${{ secrets.DEV_IP }}" "cd ./gunicorn-python-CD; python3 -m venv venv; source venv/bin/activate; sudo git pull origin master; pip install -r requirements.txt; sudo pkill gunicorn;  sudo systemctl daemon-reload systemctl; sudo systemctl restart gunicorn"

