name: Python Application CI/CD

on:
  push:
    branches: [ master ]

env:
  DEV_IP: ${{ secrets.DEV_IP }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Specify the Python version you need

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$DEV_KEY" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        ssh-keyscan "$DEV_IP" >> ~/.ssh/known_hosts
      shell: bash
      env:
        DEV_KEY: ${{ secrets.DEV_KEY }}
        DEV_IP: ${{ secrets.DEV_IP }}

    - name: Test Connection
      run: ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key root@"$DEV_IP" "echo 'SSH connection established'"

    - name: Deploy Application
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key root@"$DEV_IP" << 'EOF'
        cd /home/madhav5mar2001/dummy_app
        source venv/bin/activate  # Activate virtual environment if you have one
        pip install -r requirements.txt
        # Restart the Gunicorn service to apply the new changes
        sudo systemctl restart gunicorn
        EOF
