name: Python Application CI/CD

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.DEV_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        
      shell: bash  

    # - name: Test Connection
    #   run: ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key hp@"${{ secrets.DEV_IP }}" "echo 'SSH connection established'"

    - name: Deploy Application
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key root@"${{ secrets.DEV_IP }}" << 'EOF'
        cd ~
        if [ -d "gunicorn-python-CD" ]; then
          cd gunicorn-python-CD
          git pull
        else
          git clone https://github.com/madhav8890/gunicorn-python-CD.git
          cd gunicorn-python-CD
        fi
        # Your additional commands here, e.g., starting the server or building the project
        EOF
      shell: bash
